spring:
  application:
    name: banking-service
  datasource:
    url: jdbc:mysql://localhost:3306/banking_core_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka