server:
  port: 8085

spring:
  application:
    name: utility-payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/banking_core_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka